const lessonTitle = "小树的灵魂";

const lessonData = [
    // 正文第 1 段
    ["前年", "qián nián", "the year before last", "tahun sebelum lepas"],
    ["春节", "chūn jié", "Spring Festival", "Tahun Baru Cina"],
    ["，", "", "", ""],
    ["我从", "wǒ cóng", "I from", "saya dari"],
    ["承德的", "chéng dé de", "Chengde's", "Chengde punya"],
    ["叔叔家", "shū shu jiā", "uncle's home", "rumah pakcik"],
    ["带回", "dài huí", "brought back", "membawa pulang"],
    ["一株", "yì zhū", "a (measure word for plants)", "sebatang"],
    ["小柏树", "xiǎo bǎi shù", "little cypress tree", "pohon sedar kecil"],
    ["。", "", "", ""],
    ["小柏树", "xiǎo bǎi shù", "little cypress", "pohon sedar kecil itu"],
    ["长在", "zhǎng zài", "grows on", "tumbuh di atas"],
    ["一块", "yí kuài", "a piece of", "sebongkah"],
    ["石头上", "shí tou shàng", "stone top", "batu"],
    ["，", "", "", ""],
    ["石头", "shí tou", "stone", "batu itu"],
    ["坐在", "zuò zài", "sits in", "duduk di dalam"],
    ["托盘里", "tuō pán lǐ", "inside the tray", "dulang kecil"],
    ["，", "", "", ""],
    ["托盘里", "tuō pán lǐ", "inside the tray", "dalam dulang itu"],
    ["水幽幽存焉", "shuǐ yōu yōu cún yān", "water quietly exists therein", "air tenang bertakung di dalamnya"],
    ["，", "", "", ""],
    ["透着", "tòu zhe", "revealing / showing", "memancarkan"],
    ["殷实之气", "yīn shí zhī qì", "substantial / solid aura", "aura yang subur and makmur"],
    ["。", "", "", ""],
    ["可是", "kě shì", "But / however", "Namun begitu"],
    ["，", "", "", ""],
    ["它能在", "tā néng zài", "it can at", "ia bolehkah di"],
    ["北京", "bei jīng", "Beijing", "Beijing"],
    ["落户吗", "luò hù ma", "settle down / survive", "hidup menetap kah"],
    ["？", "", "", ""],
    ["我心里", "wǒ xīn lǐ", "in my heart", "dalam hati saya"],
    ["没有底", "méi yǒu dǐ", "had no confidence", "langsung tidak ada keyakinan"],
    ["。", "", "", ""],
    ["直到", "zhí dào", "Until", "Sehinggalah pada"],
    ["有一天", "yǒu yì tiān", "one day", "suatu hari"],
    ["，", "", "", ""],
    ["小柏树的", "xiǎo bǎi shù de", "little cypress tree's", "pohon sedar kecil itu punya"],
    ["枝条上", "zhī tiáo shàng", "on the branches", "di atas ranting dahan"],
    ["冒出", "mào chū", "sprouted out", "tumbuh keluar"],
    ["鲜绿的", "xiān lǜ de", "fresh green", "tunas hijau yang segar"],
    ["新芽时", "xīn yá shí", "new buds when", "waktu tunas baru itu"],
    ["，", "", "", ""],
    ["我才", "wǒ cái", "I only then", "barulah saya"],
    ["放下心来", "fàng xià xīn lái", "set mind at ease", "berasa lega hati"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段
    ["小柏树的", "xiǎo bǎi shù de", "Little cypress tree's", "Pohon sedar kecil itu punya"],
    ["存活", "cún huó", "survival", "kemampuan hidup"],
    ["，", "", "", ""],
    ["使我感到", "shǐ wǒ gǎn dào", "make me feel", "menyebabkan saya berasa"],
    ["养些", "yǎng xiē", "raising some", "memelihara sedikit"],
    ["木本植物", "mù bēn zhí wù", "woody plants", "tumbuhan berkayu"],
    ["该是不难吧", "gāi shì bù nán ba", "should not be difficult, right", "sepatutnya tidak susah kan"],
    ["。", "", "", ""],
    ["我便来到", "wǒ biàn lái dào", "I then came to", "Saya pun melangkah ke"],
    ["花市上", "huā shì shàng", "flower market", "pasar bunga"],
    ["，", "", "", ""],
    ["选购了", "xuǎn gòu le", "selected and bought", "memilih dan membeli"],
    ["三株", "sān zhū", "three (measure word for plants)", "tiga pohon"],
    ["盆景", "pén jǐng", "bonsai", "pokok bonsai"],
    ["——", "", "", ""],
    ["小榆树", "xiǎo yú shù", "little elm tree", "pohon elm kecil"],
    ["、", "", "", ""],
    ["小榕树", "xiǎo róng shù", "little banyan tree", "pohon beringin kecil"],
    ["和", "hé", "and", "dan"],
    ["小枫树", "xiǎo fēng shù", "little maple tree", "pohon maple kecil"],
    ["，", "", "", ""],
    ["并与", "bìng yǔ", "and with", "serta dengan"],
    ["小柏树", "xiǎo bǎi shù", "little cypress tree", "pohon sedar kecil"],
    ["一起", "yì qǐ", "together", "bersama-sama"],
    ["摆在了", "bǎi zài le", "placed on", "diletakkan di atas"],
    ["窗台上", "chuāng tái shàng", "windowsill", "ambang tingkap"],
    ["。", "", "", ""],
    ["一时间", "yī shí jiān", "For a moment / instantly", "Dalam sekelip mata"],
    ["，", "", "", ""],
    ["窗台上", "chuāng tái shàng", "on the windowsill", "di atas ambang tingkap"],
    ["郁郁葱葱", "yù yù cōng cōng", "lush green / luxuriant", "sangat hijau merimbun"],
    ["，", "", "", ""],
    ["欣欣向荣", "xīn xīn xiàng róng", "thriving / flourishing", "hidup subur menyegarkan"],
    ["，", "", "", ""],
    ["好看极了", "hǎo kàn jí le", "extremely good-looking", "tersangat cantik sekali"],
    ["。", "", "", ""],
    ["其中", "qí zhōng", "Among them", "Dalam kalangan itu"],
    ["，", "", "", ""],
    ["尤以", "yóu yǐ", "especially", "terutamanya pula"],
    ["小榕树", "xiǎo róng shù", "little banyan tree", "pohon beringin kecil"],
    ["最美", "zuì měi", "the most beautiful", "paling cantik"],
    ["。", "", "", ""],
    ["它的", "tā de", "Its", "Ia punya"],
    ["枝叶", "zhī yè", "branches and leaves", "ranting dahan dan daun"],
    ["舒展文静", "shū zhǎn wén jìng", "extended and gentle", "berkembang anggun dan tenang"],
    ["，", "", "", ""],
    ["像是", "xiàng shì", "resembles", "bagaikan / mirip"],
    ["依栏沉思的", "yī lán chén sī de", "leaning on a railing and contemplating", "wanita yang bersandar pada pagar termenung punya"],
    ["女人", "nǚ rén", "woman", "perempuan"],
    ["。", "", "", ""],
    ["小榆树", "xiǎo yú shù", "Little elm tree", "Pohon elm kecil itu"],
    ["则以", "zé yǐ", "on the other hand by means of", "pula dengan cara"],
    ["稠密而", "chóu mì ér", "dense and", "daun yang lebat dan"],
    ["热烈的", "rè liè de", "enthusiastic / warm", "meriah bertenaga punya"],
    ["叶子", "yè zi", "leaves", "daun-daun"],
    ["，", "", "", ""],
    ["显示了", "xiǎn shì le", "displayed / showed", "menunjukkan tanda"],
    ["繁荣景象", "fán róng jǐng xiàng", "prosperous scene", "pemandangan yang makmur meriah"],
    ["。", "", "", ""],
    ["小枫树", "xiǎo fēng shù", "Little maple tree", "Pohon maple kecil itu"],
    ["更是", "gèng shì", "even more", "malah lebih-lebih lagi"],
    ["风骨不俗", "fēng gǔ bù sú", "character non-commonplace", "mempunyai karakter yang mulia / tidak luhur"],
    ["，", "", "", ""],
    ["气度超然", "qì dù chāo rán", "bearing detached", "gaya pembawaan yang sangat hebat luar biasa"],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "Because", "Kerana"],
    ["它的", "tā de", "its", "ia punya"],
    ["每片叶子", "měi piàn yè zi", "every single leaf", "setiap helai daun"],
    ["都在", "dōu zài", "all currently", "semuanya sedang"],
    ["翘首以待", "qiáo shǒu yǐ dài", "raising head and eagerly waiting", "mendongak kepala ternanti-nanti akan"],
    ["那个", "nà gè", "that", "musim luruh yang"],
    ["火红的", "huǒ hóng de", "fiery red's", "merah menyala punya itu"],
    ["秋天", "qiū tiān", "autumn", "musim luruh"],
    ["。", "", "", ""],
    ["倒是", "dào shì", "Conversely / on the contrary", "Sebaliknya pula"],
    ["小柏树", "xiǎo bǎi shù", "little cypress tree", "pohon sedar kecil itu"],
    ["显得", "xiǎn de", "appeared / looked", "kelihatan"],
    ["不起眼了", "bù qǐ yǎn le", "unremarkable / ordinary", "tidak menarik perhatian langsung"],
    ["。", "", "", ""],
    ["一块", "yí kuài", "A piece of", "Sebongkah"],
    ["土里土气的", "tǔ lǐ tǔ qì de", "rustic / countrified", "batu yang comot dan buruk / ala kampung punya"],
    ["石头", "shí tou", "stone", "batu"],
    ["，", "", "", ""],
    ["一株", "yì zhū", "a branch of", "sebatang"],
    ["再普通不过的", "zài pǔ tōng bú guò de", "more ordinary than common", "ranting pohon sedar yang tersangat biasa punya"],
    ["柏树枝子", "bǎi shù zhī zi", "cypress twig", "cabang dahan"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah bagaikan"],
    ["穷山沟里", "qióng shān gōu lǐ", "inside poor mountain valleys", "anak kecil yang datang dari dalam lembah gunung miskin"],
    ["走来的", "zǒu lái de", "walked out's", "berjalan keluar punya"],
    ["孩子", "hái zi", "child", "anak"],
    ["，", "", "", ""],
    ["有些", "yǒu xiē", "somewhat", "ada sedikit rasa"],
    ["相形见绌", "xiāng xíng jiàn chù", "pale by comparison", "kurang setanding apabila dibandingkan"],
    ["。", "", "", ""],
    ["好在", "hǎo zài", "Fortunately / luckily", "Mujurlah nasib baik"],
    ["它", "tā", "it", "ia"],
    ["“要求于人的甚少”", "yāo qù yú rén de shèn shǎo", "demands very little from others", "meminta keperluan daripada orang tersangat sedikit"],
    ["，", "", "", ""],
    ["只要", "zhǐ yào", "as long as", "asalkan di dalam"],
    ["托盘里", "tuō pán lǐ", "inside the tray", "dulang kecil itu"],
    ["有点水", "yǒu diǎn shuǐ", "has some water", "ada sedikit air"],
    ["就行了", "jiù háng le", "then will do", "dah memadai dah"],
    ["，", "", "", ""],
    ["什么心", "shén me xīn", "any worry / mind", "apa jua kerisauan hati"],
    ["也不用操", "yě  bú yòng cāo", "also no need to worry", "pun tidak payah nak difikirkan belaka"],
    ["。", "", "", ""],
    ["另外三株", "lìng wài sān zhū", "The other three plants", "Manakala tiga pohon yang lain itu"],
    ["就不同", "jiù bù tóng", "then was different", "pula tersangat berbeza"],
    ["，", "", "", ""],
    ["施肥浇水", "shī féi jiāo shuǐ", "fertilizing and watering", "membaja gembur jirus air"],
    ["，", "", "", ""],
    ["喜阴喜阳", "xǐ yīn xǐ yáng", "preference for shade or sun", "suka tempat teduh atau matahari"],
    ["，", "", "", ""],
    ["很有些", "hěn yǒu xiē", "quite had some", "memang ada banyak"],
    ["讲究", "jiǎng jiu", "fastidious", "peraturan dan tertibnya"],
    ["。", "", "", ""],
    ["就是", "jiù shì", "Even / precisely", "Malah sehinggakan waktu"],
    ["浇水", "jiāo shuǐ", "watering", "menjirus air"],
    ["也", "yě", "also", "pun"],
    ["不能大意", "bù néng dà yì", "cannot be careless", "tidak boleh ambil lewa / cuai"],
    ["，", "", "", ""],
    ["弄不好", "nòng bù hǎo", "if not handled well", "kalau tersilap haribulan nanti"],
    ["还会", "hái huì", "even would", "pasti akan"],
    ["烂根", "làn gēn", "rot roots", "membusuk akarnya"],
    ["。", "", "", ""],
    ["为此", "wèi cǐ", "Because of this", "Oleh sebab hal ini"],
    ["，", "", "", ""],
    ["我真", "wǒ zhēn", "I truly", "saya sungguh-sungguh"],
    ["请教了", "qǐng jiào le", "consulted", "pernah berguru / meminta nasihat daripada"],
    ["不少花匠", "bù shǎo huā jiàng", "many gardeners", "ramai tukang kebun bunga"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段
    ["谁知", "shéi zhī", "Who knew / unexpectedly", "Siapa sangka / rupa-rupanya luar jangkaan"],
    ["，", "", "", ""],
    ["越是", "yuè shì", "the more", "semakin kita"],
    ["竭尽", "jié jìn", "exhaust completely", "mencurahkan sehabis-habis"],
    ["呵护之能事", "hē hù zhī néng shì", "utmost care and protection", "daya upaya bela belai penjagaan"],
    ["，", "", "", ""],
    ["越是", "yuè shì", "the more", "maka semakin pula"],
    ["容易", "róng yì", "easy to", "mudah untuk"],
    ["出问题", "róng yì chū wèn tí", "happen problems", "timbul masalah penyakit"],
    ["。", "", "", ""],
    ["还不到", "hái bú dào", "Still not yet arrived at", "Belum pun sempat sampai ke"],
    ["秋天", "qiū tiān", "autumn", "musim luruh"],
    ["，", "", "", ""],
    ["小枫树的", "xiǎo fēng shù de", "little maple tree's", "pohon maple kecil itu punya"],
    ["叶子", "yè zi", "leaves", "daun-daun"],
    ["忽然", "tū rán", "suddenly", "tiba-tiba sahaja"],
    ["打卷了", "dǎ juǎn le", "curled up", "dah menggulung mengecut"],
    ["，", "", "", ""],
    ["有的", "yǒu de", "some", "ada sebahagian antaranya"],
    ["还变黑", "hái biàn hēi", "even turned black", "turut menjadi hitam legam"],
    ["，", "", "", ""],
    ["一幅", "yí fù", "a look of", "satu rupa keadaan yang"],
    ["病兮兮的", "bìng xī xī de", "sickly", "sakit tenat / layu bernyawa buruk"],
    ["样子", "yàng zi", "appearance", "rupa"],
    ["。", "", "", ""],
    ["我赶紧", "wǒ gǎn jǐn", "I hurriedly", "Saya dengan segera bergegas"],
    ["四处", "sì chù", "everywhere", "merata-rata tempat"],
    ["求医", "qiú yī", "seek treatment", "mencari penawar ubat"],
    ["，", "", "", ""],
    ["忙着", "māng zhe", "busy doing", "sibuk ke sana kemari"],
    ["打药治疗", "dǎ yào zhì liáo", "spraying medicine to treat", "menyembur racun serangga merawat"],
    ["，", "", "", ""],
    ["盼着它", "pàn zhe tā", "hoping it to", "berharap bersungguh-sungguh agar ia"],
    ["“春风又绿”", "chūn fēng yòu lǜ", "spring breeze green again", "kembali segar bugar bagaikan ditiup bayu musim bunga"],
    ["。", "", "", ""],
    ["然而", "rán ér", "However", "Namun begitu nyata sekali"],
    ["，", "", "", ""],
    ["可叹它", "kě tàn tā", "lamentably it", "alangkah sayunya ia punya keadaan"],
    ["一日不似一日", "yí rì bú sì yí rì", "getting worse day by day", "hari demi hari semakin merosot teruk"],
    ["，", "", "", ""],
    ["眼见着", "yǎn jiàn zhe", "watching with own eyes", "melihat dengan mata kepala sendiri"],
    ["一片片叶子", "yí piàn piàn yè zi", "piece after piece of leaves", "sehelai demi sehelai daunnya"],
    ["都卷了", "dōu juǎn le", "all curled up", "semuanya menggulung kecut"],
    ["起来", "qǐ lái", "up", "mula"],
    ["，", "", "", ""],
    ["小枫树", "xiǎo fēng shù", "little maple tree", "pohon maple kecil itu"],
    ["到底", "dào dǐ", "in the end / finally", "akhirnya kesudahannya"],
    ["一命呜呼了", "yí mìng wū hū le", "passed away", "telah mati gugur langsung / tamat riwayat nyawa"],
    ["。", "", "", ""],
    ["我也", "wǒ yě", "I also", "Saya pun turut"],
    ["好生", "hǎo shēng", "quite / deeply", "berasa tersangat"],
    ["伤感", "shāng gǎn", "sorrowful", "sedih luluh hati"],
    ["，", "", "", ""],
    ["原本", "yuán bǎn", "originally", "pada asalnya"],
    ["我还期待着", "wǒ hái qī dài zhe", "I still looked forward to", "saya asyik tertunggu-tunggu memasang angan-angan"],
    ["坐在屋里", "zuò zài wū lǐ", "sitting inside the room", "duduk di dalam bilik rumah"],
    ["独赏红叶呢", "dú shǎng hóng yè ne", "solely appreciating red autumn leaves", "menikmati keindahan daun merah seorang diri lah"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段
    ["秋天", "qiū tiān", "Autumn", "Musim luruh"],
    ["过去了", "guò qù le", "passed away", "dah berlalu pergi"],
    ["，", "", "", ""],
    ["天气", "tiān qì", "weather", "keadaan cuaca"],
    ["渐渐", "jiàn jiàn", "gradually", "perlahan-lahan / lama-kelamaan"],
    ["冷起来", "lěng qǐ lái", "turned cold up", "mula menjadi sejuk dingin"],
    ["。", "", "", ""],
    ["小榆树", "xiǎo yú shù", "Little elm tree", "Pohon elm kecil"],
    ["和", "hé", "and", "dan"],
    ["小榕树的", "xiǎo róng shù de", "little banyan tree's", "pohon beringin kecil punya"],
    ["叶子", "yè zi", "leaves", "daun-daun"],
    ["越来越少了", "yuè lái yuè shǎo le", "getting less and less", "menjadi semakin hari semakin berkurangan sedikit sudah"],
    ["。", "", "", ""],
    ["一场雪后", "yī cháng xuě hòu", "After a snowfall", "Selepas berlakunya sekali kejadian turun salji"],
    ["，", "", "", ""],
    ["它们的", "tā men de", "their", "mereka punya"],
    ["叶子", "yè zi", "leaves", "daun-daun"],
    ["几乎", "jī hū", "almost / nearly", "boleh dikatakan hampir"],
    ["全干了", "quán gān le", "all dried up", "semuanya dah kering kontang kekeringan"],
    ["，", "", "", ""],
    ["便想", "biàn xiǎng", "then thought to oneself", "lalu saya berfikir sendirian"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["大概是", "dà gài shì", "Probably it is", "Barangkali ini merupakan baki"],
    ["冬眠吧", "dōng mián ba", "hibernation, right", "tidur musim sejuk (hibernasi) lah"],
    ["。”", "", "", ""],
    ["而我", "ér wǒ", "And I", "Manakala saya pula"],
    ["依然", "yī rán", "still / as before", "tetap masih kekal kekal"],
    ["按时", "àn shí", "on schedule", "mengikut ketetapan masa"],
    ["浇水", "jiāo shuǐ", "watering", "menjirus air"],
    ["，", "", "", ""],
    ["尽职尽责", "jìn zhí jìn zé", "dutifully fulfilling responsibility", "menjalankan tanggungjawab tugas dengan sehabis baik"],
    ["，", "", "", ""],
    ["以待", "yǐ dài", "in order to wait for", "demi ternanti-nanti ketibaan"],
    ["来年", "lái nián", "coming year", "tahun hadapan kelak"],
    ["春暖花开时", "chūn nuǎn huā kāi shí", "spring warms up and flowers bloom when", "waktu cuaca musim bunga hangat dan bunga-bunga berkembang mendatar"],
    ["，", "", "", ""],
    ["让它们", "ràng tā men", "let them", "menyebabkan mereka semua"],
    ["再吐新绿", "zài tǔ xīn lǜ", "again spit fresh green", "kembali menumbuhkan keluar tunas hijau yang baru"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段
    ["然而", "rán ér", "Horizontal / yet", "Namun begitu segala-galanya meleset"],
    ["，", "", "", ""],
    ["它们", "tā men", "they", "pohon-pohon itu semua"],
    ["再也没有", "zài yě méi yǒu", "never again", "langsung tidak pernah lagi jua"],
    ["醒来", "xǐng lái", "woke up", "terbangun sedar semula"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段
    ["如今", "rú jìn", "now", "Sekarang pada saat ini sudah"],
    ["，", "", "", ""],
    ["小榆树", "xiǎo yú shù", "little elm tree", "pohon elm kecil"],
    ["，", "", "", ""],
    ["小榕树", "xiǎo róng shù", "little banyan tree", "pohon beringin kecil"],
    ["，", "", "", ""],
    ["小枫树的", "xiǎo fēng shù de", "little maple tree's", "pohon maple kecil punya baki"],
    ["“遗骨”", "yí gǔ", "remains", "rangka sisa mayat kayu buruk"],
    ["陈列在", "chén liè zài", "displayed inside", "terpamer kaku tersusun di atas"],
    ["阳台上", "yáng tái shàng", "balcony top", "balkoni luar rumah"],
    ["，", "", "", ""],
    ["好像", "xiàng hǎo", "resembles", "bagaikan / seolah-olah rupa rupa"],
    ["三块", "sān kuài", "three pieces of", "tiga buah"],
    ["墓碑", "mù bēi", "tombstones", "batu nisan kubur"],
    ["，", "", "", ""],
    ["让人", "ràng rén", "make people", "menyebabkan orang melihatnya berasa"],
    ["神伤", "shén shāng", "heartbroken", "tersangat sayu luluh jiwa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段
    ["这时", "zhè shí", "At this moment", "Pada waktu sebegini yang ini"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["却", "què", "surprisingly", "pula sebaliknya"],
    ["不得不", "bù dé bù", "cannot but", "tidak dapat tidak terpaksa juga"],
    ["惊异于", "jīng yì yu", "be astonished by", "berasa tersangat kagum dan hairan luar biasa terhadap"],
    ["小柏树的", "xiǎo bǎi shù de", "little cypress tree's", "pohon sedar kecil itu punya"],
    ["生命力了", "shēng mìnɡ lì le", "vitality", "daya kekuatan untuk terus hidup ketahanan nyawa"],
    ["。", "", "", ""],
    ["只见它", "zhǐ jiàn tā", "Only to see it", "Hanya kelihatan ia punya"],
    ["所有的", "suǒ yǒu de", "all's", "keseluruhan belaka"],
    ["叶端", "yè duān", "tips of leaves", "hujung-hujung daun"],
    ["纷纷", "fēn fēn", "one after another", "ramai-ramai / bertumpu-tumpu"],
    ["吐出了", "tǔ chū le", "spitted out", "telah menumbuhkan keluar"],
    ["新绿", "xīn lǜ", "fresh green", "tunas hijau yang baru"],
    ["，", "", "", ""],
    ["鲜活鲜活的", "xiān huó xiān huó de", "vibrant and fresh alive", "yang tersangat segar bugar hidup"],
    ["耀眼极了", "yào yǎn jí le", "extremely dazzling", "menyilaukan pandangan mata sekali"],
    ["，", "", "", ""],
    ["竟有一种", "jìng yǒu yì zhǒng", "unexpectedly possessed a kind of", "malah rupa-rupanya mempunyai sejenis"],
    ["光芒四射的", "guāng māng sì shè de", "radiant", "sinaran cahaya gemilang yang memancar ke segenap penjuru punya"],
    ["神采", "shén cǎi", "mental glow", "gaya pembawaan dan seri wajah makmur"],
    ["，", "", "", ""],
    ["令人", "lìng rén", "make people", "menyebabkan setiap orang yang memandang berasa"],
    ["激赏", "jī shǎng", "highly appreciate", "amat memuji kagum"],
    ["，", "", "", ""],
    ["令人", "lìng rén", "make people", "menyebabkan orang berasa"],
    ["感奋", "gǎn fèn", "inspired and excited", "terangsang bersemangat kencang semula"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段
    ["我", "wǒ", "I", "Saya"],
    ["禁不住", "bù jǐn zhù", "cannot help but", "tidak dapat menahan diri lalu terus"],
    ["把小柏树", "bǎ xiǎo bǎi shù", "little cypress tree", "membawa pohon sedar kecil itu"],
    ["搬到", "bān dào", "moved to", "dipindahkan letak ke atas"],
    ["写字台上了", "xiě zì tái shàng", "writing desk top", "meja tulis tempat kerja"],
    ["，", "", "", ""],
    ["仔细", "zǐ xì", "carefully / meticulously", "dengan penuh teliti and khusyuk"],
    ["端详起来", "duān xiáng qǐ lái", "scrutinized", "memerhati menatap rupa parasnya"],
    ["。", "", "", ""],
    ["我发现", "wǒ fā xiàn", "I discovered", "Saya mendapati menyedari bahawa"],
    ["它", "tā", "it", "ia rupa-rupanya"],
    ["竟然是", "jìng rán shì", "unexpectedly was", "luar jangkaan benar-benar adalah"],
    ["从石头缝里", "cóng shí tou fèng lǐ", "from inside the stone crack", "tumbuh membesar keluar dari dalam celah retakan batu"],
    ["长出来的", "zhǎng chū lái de", "grown out's", "itu punya"],
    ["。 ", "", "", ""],
    ["那石头的", "nà shí tou de", "That stone's", "Batu itu punya"],
    ["下半截", "xià bàn jié", "lower half segment", "bahagian potongan sebelah bawah"],
    ["分明", "fēn míng", "clearly", "secara terang-terangan nyata sekali"],
    ["有一道", "yǒu yí dào", "has a", "mempunyai sebaris jajaran"],
    ["裂缝", "liè fèng", "crack", "celah retakan parah"],
    ["，", "", "", ""],
    ["裂缝里", "liè fèng lǐ", "inside the crack", "di dalam celah retakan itu"],
    ["布满了", "bù mǎn le", "fully covered with", "sarat dipenuhi berselirat oleh"],
    ["小柏树的", "xiǎo bǎi shù de", "little cypress tree's", "pohon sedar kecil itu punya"],
    ["根须", "gēn xū", "root filaments", "urat-urat rambut akar dahan"],
    ["，", "", "", ""],
    ["根须之密", "gēn xū zhī mì", "density of the root filaments", "kelebatan jalinan urat akarnya yang tersangat padat itu"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah bagaikan"],
    ["老寿星的", "lǎo shòu xīng de", "Old Immortal's", "janggut dewa panjang umur (Lao Shouxing) punya"],
    ["胡子", "hú zi", "beard", "janggut panjang"],
    ["，", "", "", ""],
    ["又仿佛", "yòu fǎng fú", "and again as if", "dan ditumpu pula bagaikan"],
    ["网一样的", "wǎng yí yàng de", "net-like", "jalinan sarang pukat jaring punya"],
    ["脉络", "mài luò", "veins", "jaluran urat saraf pembuluh jalinan"],
    ["。", "", "", ""],
    ["它们", "tā men", "They", "Urat-urat akar itu semua"],
    ["裸露着", "luǒ lù zhe", "exposed nakedly", "terdedah gondol tanpa sebarang pelindung"],
    ["，", "", "", ""],
    ["有如", "yǒu rú", "just like", "bagaikan mirip semestinya"],
    ["丰富的", "fēng fù de", "abundant", "jaringan sistem urat saraf yang tersangat kaya and lebat"],
    ["神经", "shén jīng", "nerves", "saraf badan"],
    ["系着", "xì zhe", "fastened to", "sedang mengikat memegang erat"],
    ["一颗", "yì kē", "a", "seulas sekeping"],
    ["美丽的", "mèi lì de", "beautiful's", "jiwa sanubari yang amat murni and murni punya"],
    ["灵魂", "líng hún", "soul", "jiwa"],
    ["，", "", "", ""],
    ["我的心", "wǒ de xīn", "my heart", "lubuk hati saya yang dalam"],
    ["被这个", "bèi zhè ge", "by this", "telah oleh pihak sanubari jiwa yang satu ini punya"],
    ["灵魂", "líng hún", "soul", "jiwa"],
    ["深深触动着", "shēn shēn chù dòng zhe", "deeply touched currently", "benar-benar tersentuh meresap ke dalam belaka"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段
    ["是的", "shì de", "Yes / indeed", "Ya, memang benar semestinya"],
    ["，", "", "", ""],
    ["树", "shù", "trees", "setiap pohon tumbuhan"],
    ["是有", "shì yǒu", "do have", "memang mempunyai buah"],
    ["灵魂的", "líng hún de", "souls", "jiwa sanubarinya sendiri"],
    ["。", "", "", ""],
    ["人类", "rén lèi", "Human race", "Umat manusia sedunia"],
    ["从", "cóng", "ever since from", "sejak semenjak dari zaman melakukan"],
    ["“树神崇拜”", "shù shén chóng bài", "tree deity worship", "adat sembah puja dewa pokok (animisme)"],
    ["时", "shí", "time when", "waktu purba itu lagi"],
    ["就这样", "jiù zhè yàng", "already in this way", "dah sentiasa berpegang iktikad"],
    ["认为着", "rèn wéi zhe", "believing currently", "memikirkan berpandangan sedemikian"],
    ["，", "", "", ""],
    ["古希腊的", "gǔ xī là de", "Ancient Greece's", "Zaman Yunani Purba punya pakar bernama"],
    ["亚里斯多德", "yà lǐ sī duō dé", "Aristotle", "Aristotle"],
    ["也说过", "yě shuō guò", "also said before", "pun pernah mengeluarkan sabda berkata bahawa"],
    ["“植物是有灵魂的”", "zhí wù shì yǒu líng hún de", "plants do have souls", "tumbuhan-tumbuhan herba hijau pun mempunyai jiwa sanubari jua"],
    ["，", "", "", ""],
    ["不过", "bú guò", "but / however", "namun begitu watak watak"],
    ["它们的", "tā men de", "their", "mereka punya baki"],
    ["灵魂", "líng hún", "souls", "jiwa sanubari"],
    ["却", "què", "surprising", "pula sebaliknya adalah"],
    ["有所不同", "yǒu suǒ bù tóng", "somewhat different", "mempunyai sedikit perbezaan tak seiras"],
    ["，", "", "", ""],
    ["正如", "zhèng rú", "just as", "bagaikan / mirip mirip"],
    ["人世间", "rén shì jiān", "human world", "di atas alam dunia fana manusia ini"],
    ["有着", "yǒu zhe", "possessing", "mempunyai sarat"],
    ["形形色色的", "xíng xíng sè sè de", "all kinds of", "berbagai-bagai corak jenis rupa paras punya"],
    ["灵魂", "líng hún", "souls", "jiwa sanubari jua"],
    ["。", "", "", ""],
    ["然而", "rán ér", "However / yet", "Namun begitu nyata sekali"],
    ["，", "", "", ""],
    ["一个", "yí gè", "a", "sesosok seulas"],
    ["美丽的", "mèi lì de", "beautiful's", "yang murni and cantik punya"],
    ["灵魂", "líng hún", "soul", "jiwa sanubari"],
    ["却是", "què shì", "conversely is", "sebaliknya adalah wajib wajib"],
    ["需要", "xū yào", "requiring", "memerlukan jalan baki"],
    ["历练的", "lì liàn de", "tempering", "melalui fasa latihan lasak asam garam dugaan hidup punya"],
    ["。", "", "", ""],
    ["小柏树", "xiǎo bǎi shù", "Little cypress tree", "Pohon sedar kecil itu"],
    ["一定是", "yí dìng充实", "definitely was", "pasti semestinya sudah lama sangat"],
    ["历练过的", "lì liàn guò de", "experienced and tempered through", "melalui fasa ujian lasak hidup punya"],
    ["，", "", "", ""],
    ["否则", "fǒu zé", "otherwise", "jika tidak demikian halnya"],
    ["它不会", "tā bú huì", "it would not", "ia tidak akan berupaya"],
    ["有这样", "yǒu zhè yàng", "possess this kind of", "mempunyai gaya pembawaan watak sebegini"],
    ["叫人", "jiào rén", "make people", "yang menyebabkan setiap orang yang memandang terkapas"],
    ["暗暗尊敬的", "àn àn zūn jìnɡ de", "secretly respect's", "menaruh rasa hormat yang mendalam di dalam hati punya"],
    ["树品", "shù pǐn", "tree character", "martabat watak integriti pohon (树品)"],
    ["。", "", "", ""],
    ["其实", "qí shí", "Actually / in fact", "Pada hakikatnya yang sebenar"],
    ["，", "", "", ""],
    ["它的", "tā de", "its", "ia punya baki martabat"],
    ["树品", "shù pǐn", "tree character", "watak integriti pohon"],
    ["本来就", "běn lái jiù", "originally long ago already", "memang pada asalnya semenjak azali lagi dah"],
    ["有着", "yǒu zhe", "possessed", "mempunyai khazanah jalinan"],
    ["悠远的", "yōu yuǎn de", "distant", "galur keturunan yang tersangat panjang and kuno punya"],
    ["脉系", "mài xì", "lineage", "jaluran silsilah keturunan darah (脉系)"],
    ["。", "", "", ""],
    ["《山海经》", "shān hǎi jīng", "Classic of Mountains and Seas", "Kitab Klasik Sanhaijing"],
    ["记载", "jì zǎi", "recorded", "ada mencatatkan piagam surat bahawa"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["白於之山", "bái yú zhī shān", "Baiyu Mountain", "Gunung Baiyu"],
    ["，", "", "", ""],
    ["其上", "qí shàng", "its top", "di atas kemuncaknya itu"],
    ["多柏", "duō bǎi", "abundant cypresses", "sarat ditumbuhi banyak pokok sedar"],
    ["。”", "", "", ""],
    ["《国语》", "guó yǔ", "Discourses of the States", "Kitab Klasik Guoyu"],
    ["曰", "yuē", "stated", "ada bersabda menyatakan kalam"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["松柏之地", "sōng bǎi zhī dì", "land of pines and cypresses", "Kawasan tanah tempat pokok pain and sedar membesar"],
    ["，", "", "", ""],
    ["其土", "qí tǔ", "its soil", "tanah buminya itu kebetulan"],
    ["不肥", "bù féi", "not fertile", "adalah gersang / tidak subur bermbaja langsung"],
    ["。”", "", "", ""],
    ["至于", "zhì yú", "As for / regarding", "Sehinggalah membawa kepada ungkapan madah"],
    ["“", "", "", ""],
    ["柏经冬", "bǎi jīng dōng", "cypress passes winter", "pohon sedar apabila melalui fasa beku musim sejuk"],
    ["而不凋", "ér bù diāo", "and yet does not wither", "tetap masih kekal utuh / langsung tidak gugur layu"],
    ["，", "", "", ""],
    ["蒙霜不变", "méng shuāng bú biàn", "covered in frost yet unchanged", "diselimuti ibun salji tebal pun rupa warnanya langsung tidak bertukar kelat"],
    ["，", "", "", ""],
    ["可谓得其真也", "kě wèi得真也", "can be said to have obtained its true essence indeed", "boleh disifatkan sebagai berjaya merangkul hakikat jati diri yang sejati belaka lah"],
    ["。”", "", "", ""],
    ["的", "de", "particle", ""],
    ["说法", "shuō fǎ", "assertions", "ulasan hujah pandangan orang tua"],
    ["就更多了", "jiù gèng duō le", "then was even more", "maka dah bertambah-tambah banyak gila jua sudah"],

    ["\n", "", "", ""], // 👈 第 10 段
    ["还有", "hái yǒu", "There is also", "Malah ada terkandung lagi satu buah"],
    ["一个说法", "yí gè shuō fǎ", "a phrasing", "ulasan kata madah hikmat"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ia semestinya adalah datang dari"],
    ["古代画论", "gǔ dài huà lùn", "ancient painting theories", "kitab teori seni lukis purba lama punya kalam"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["人品", "rén pǐn", "human moral character status", "integriti martabat watak moral manusia (人品)"],
    ["既已高矣", "jì yǐ gāo yǐ", "since already elevated", "memandangkan sudah sedia berada di tahap yang tinggi mulia"],
    ["，", "", "", ""],
    ["气韵", "qì yùn", "artistic charm", "gaya aura kesenian and karisma murni (气韵)"],
    ["不得不高", "qì yùn bù dé bù gāo", "has to be elevated", "tidak dapat tidak terpaksa turut menjadi tinggi luhur jua"],
    ["；", "", "", ""],
    ["气韵", "qì yùn", "artistic charm", "karisma gaya aura murni kesenian itu pula"],
    ["既已高矣", "jì yǐ gāo yǐ", "since already elevated", "memandangkan sudah sedia berada di tahap mulia gilang-gemilang"],
    ["，", "", "", ""],
    ["生动", "shēng dòng", "vividness", "nyawa yang hidup berseri-seri segar bugar"],
    ["不得不至", "shēng dòng bù dé bù zhì", "has to arrive", "tidak dapat tidak terpaksa melangkah sampai ke puncak makmur"],
    ["。”", "", "", ""],
    ["我想", "wǒ xiǎng", "I think", "Saya membuat hujah kesimpulan berfikir"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["人品如此", "rén pǐn rú cǐ", "human character is in this way", "integriti martabat watak manusia adalah sedemikian rupa berkeadaan"],
    ["，", "", "", ""],
    ["树品亦然", "shù pǐn yì rán", "tree character is also the same", "maka martabat watak integriti pohon (树品) pun tetap serupa semata-mata"],
    ["。”", "", "", ""],
    ["只可惜", "zhǐ kě xī", "Only unfortunately", "Namun tersangat sayang and rugi sekali kesal"],
    ["我与小柏树", "wǒ yǔ xiǎo bǎi shù", "I and little cypress tree", "saya dengan pohon sedar kecil ini punya hubungan"],
    ["相伴", "xiāng bàn", "accompanied each other", "saling berteman akrab mendatar"],
    ["一年有余", "yì nián yǒu yú", "more than a year", "selama setahun lebih sedikit sudah"],
    ["，", "", "", ""],
    ["竟如此", "jì rú cǐ", "unexpectedly in this way", "bisa rupa-rupanya keadaannya sebegitu rupa rupa"],
    ["赏悟不敏", "shǎng wù bù mǐn", "dull in appreciation", "tersangat tumpul akal, lambat and bodoh dalam menghargai meneliti falsafah jiwanya"],
    ["，", "", "", ""],
    ["实在是", "shí zài shì", "truly was", "adalah seikhlasnya benar--benar merupakan suatu perbuatan"],
    ["徒知", "tú zhī", "merely knowing", "hanya sekadar pandai tahu akan kewujudan hakikat"],
    ["人之有神", "rén zhī yǒu shén", "humans having divine spirit", "umat manusia mempunyai aura minda and roh jiwa"],
    ["，", "", "", ""],
    ["而不知", "ér bù zhī", "and yet not knowing", "sebaliknya langsung tidak celik tahu akan hakikat"],
    ["树之有神", "shù zhī yǒu shén", "trees having divine spirit", "pohon-pohon pun mempunyai aura minda roh jiwanya yang tersinidri jua"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段
    ["失敬了", "shī jìng le", "I owe you an apology", "Mohon maaf zahir batin atas kebiadaban lambat sedar hamba yang tidak menaruh hormat selama ini"],
    ["，", "", "", ""],
    ["小柏树", "xiǎo bǎi shù", "little cypress tree", "wahai pohon sedar kecil kesayanganku"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 出处
    ["（", "", "", ""],
    ["于源", "yú yuán", "Yu Yuan (Author)", "Yu Yuan (Penulis)"],
    ["《", "", "", ""],
    ["小树的", "xiǎo shù de", "Little Tree's", "Jiwa Sanubari"],
    ["灵魂", "líng hún", "Soul", "Pohon Kecil"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
